Repository newjersey/dol-my-career-nj, pull requests merged in 2023-07, with the labels that each got.

#1084 Training explorer update
  backend/package-lock.json
  frontend/cypress/e2e/search.cy.js
  frontend/cypress/e2e/training-explorer.cy.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/HowTo.tsx
  frontend/src/components/Interrupter.tsx
  frontend/src/components/PageBanner.tsx
  frontend/src/components/SearchBlock.test.tsx
  frontend/src/components/SearchBlock.tsx
  frontend/src/components/Stepper.tsx
  frontend/src/components/modules/PhosphorIconSelector.tsx
  frontend/src/fence.json
  frontend/src/filtering/ClassFormatFilter.tsx
  frontend/src/filtering/CostFilter.tsx
  frontend/src/filtering/LocationFilter.tsx
  frontend/src/landing-page/LandingPage.test.tsx
  frontend/src/landing-page/LandingPage.tsx
  frontend/src/queries/trainingExplorer.ts
  frontend/src/styles/colors.scss
  frontend/src/styles/components/_footer-cta.scss
  frontend/src/styles/components/_how-to.scss
  frontend/src/styles/components/_interrupter.scss
  frontend/src/styles/components/_page-banner.scss
  frontend/src/styles/components/_search-block.scss
  frontend/src/styles/components/_stepper.scss
  frontend/src/styles/index.scss
  frontend/src/styles/landing-page.scss
  frontend/src/styles/modules/_accordion.scss
  frontend/src/svg/Icons/ExploreBold.tsx
  frontend/src/svg/Icons/JobsBold.tsx
  frontend/src/svg/Icons/SupportBold.tsx
  frontend/src/svg/Icons/TrainingBold.tsx
  frontend/src/svg/Selector.tsx
  frontend/src/types/contentful.ts
  frontend/src/types/icons.ts
Labels: Ready for Review, MVP Launch

#1090 Occupation details
  backend/src/domain/contentful/queries.ts
  frontend/cypress/e2e/career-pathways-page.cy.js
  frontend/src/career-pathways-page/CareerPathwaysPage.tsx
  frontend/src/components/Accordion.tsx
  frontend/src/components/FaqCollection.tsx
  frontend/src/components/IndustryBlock.tsx
  frontend/src/components/IndustrySelector.tsx
  frontend/src/components/OccupationBlock.tsx
  frontend/src/error/ErrorPage.tsx
  frontend/src/styles/colors.scss
  frontend/src/styles/components/_occupation-block.scss
  frontend/src/styles/index.scss
  frontend/src/styles/modules/_error-message.scss
  frontend/src/types/contentful.ts
  frontend/src/utils/calendarLength.ts
  frontend/src/utils/numberWithCommas.ts
  frontend/src/utils/toUsCurrency.ts
  frontend/src/utils/useWindowWidth.ts
Labels: MVP Launch

#1220 Update TrainingPage.tsx
  frontend/src/training-page/TrainingPage.tsx
Labels: Ready for Review

#1219 assets added
  backend/src/domain/contentful/queries.ts
  frontend/src/components/ContentfulRichText.tsx
  frontend/src/components/TabContent.tsx
  frontend/src/types/contentful.ts
Labels: Ready for Review

#1111 [NJWE-681] Add "Total Clock Hours" value to Training Programs Details page
  backend/package-lock.json
  backend/src/database/data/PostgresDataClient.test.ts
  backend/src/database/data/PostgresDataClient.ts
  backend/src/domain/occupations/getOccupationDetail.test.ts
  backend/src/domain/search/searchTrainings.test.ts
  backend/src/domain/search/searchTrainings.ts
  backend/src/domain/test-objects/factories.ts
  backend/src/domain/training/Program.ts
  backend/src/domain/training/Training.ts
  backend/src/domain/training/TrainingResult.ts
  backend/src/domain/training/convertTrainingToTrainingResult.ts
  backend/src/domain/training/findTrainingsBy.test.ts
  backend/src/domain/training/findTrainingsBy.ts
  frontend/cypress/e2e/training-page.cy.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/domain/Training.ts
  frontend/src/locales/en.ts
  frontend/src/locales/es.ts
  frontend/src/styles/training-page.scss
  frontend/src/test-objects/factories.ts
  frontend/src/training-page/TrainingPage.test.tsx
  frontend/src/training-page/TrainingPage.tsx
Labels: Ready for Review, Pre-MVP

#1256 [NJWE-964] Implement In-demand by county tags on Training Details Page
  backend/package-lock.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/__tests__/WaiverBlock.test.tsx
  frontend/src/locales/en.ts
  frontend/src/locales/es.ts
  frontend/src/occupation-page/OccupationPage.test.tsx
  frontend/src/training-page/TrainingPage.tsx
Labels: Not ready, Pre-MVP
